version: '3.2'
services:  
  ooh.ims.services:
   build:
     context: ./ims
     dockerfile: Dockerfile
   ports:
     - "8080:3000"
   depends_on:
     - ooh.ims.db
  ooh.ims.db:
   build:
     context: ./db
     dockerfile: Dockerfile
   restart: always
   environment: 
     - POSTGRES_DB=oohdb
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
   ports:
     - "5432:5432"
   volumes:
    - ./var/lib/postgresql/data
